require('dotenv').config();
const dbConnect = require('../config/db');
const GoodsModel = require('../models/Goods');

dbConnect();
function seeder1() {
  GoodsModel.insertMany([
    {
      name: 'Сосновый бор',
      author: '5fe050d48af2d06b642f117c',
      authorName: 'Andrei Balandin',
      year: '2020',
      material: 'Графика',
      size: 100,
      article: 'I00001',
      sizeFilter: '1',
      price: 1900,
      color: 'Оранжевый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Andrei Balandin',
    },
    {
      name: 'Утро',
      author: '5fe050d48af2d06b642f117c',
      authorName: 'Andrei Balandin',
      year: '2020',
      sizeFilter: '2',
      material: 'Графика',
      size: 200,
      article: 'I00002',
      price: 3900,
      color: 'Фиолетовый',
      picture: 'https://imagizer.imageshack.com/img924/6148/w67jNq.jpg',
      description: 'Работа Andrei Balandin',
    },
    {
      name: 'Весна',
      author: '5fe050d48af2d06b642f117c',
      authorName: 'Andrei Balandin',
      year: '2020',
      material: 'Живопись',
      size: 300,
      sizeFilter: '1',
      article: 'I00003',
      price: 3900,
      color: 'Розовый',
      picture: 'https://imagizer.imageshack.com/img922/1753/cNKAwj.jpg',
      description: 'Работа Andrei Balandin',
    },
    {
      name: 'Лето',
      author: '5fe050d48af2d06b642f117c',
      authorName: 'Andrei Balandin',
      year: '2020',
      material: 'Живопись',
      size: 20,
      sizeFilter: '1',
      article: 'I00004',
      price: 9900,
      color: 'Оранженый',
      picture: 'https://imagizer.imageshack.com/img924/6936/UDg5kw.jpg',
      description: 'Работа Andrei Balandin',
    },
    {
      name: 'Зима',
      author: '5fe050d48af2d06b642f117c',
      authorName: 'Andrei Balandin',
      year: '2020',
      material: 'Инсталляция',
      size: 30,
      article: 'I00005',
      sizeFilter: '2',
      price: 9900,
      color: 'Зеленый',
      picture: 'https://imagizer.imageshack.com/img924/6360/eCYRBt.jpg',
      description: 'Работа Andrei Balandin',
    },
    {
      name: 'Красота внутри тебя',
      author: '5fe050d48af2d06b642f117c',
      authorName: 'Andrei Balandin',
      year: '2020',
      material: 'Инсталляция',
      size: 10,
      article: 'I00006',
      sizeFilter: '1',
      price: 4900,
      color: 'Черно-белый',
      picture: 'https://imagizer.imageshack.com/img923/2365/fil2hs.jpg',
      description: 'Работа Andrei Balandin',
    },

    {
      name: 'Машины и город и красота',
      author: '5fe050d48af2d06b642f117c',
      authorName: 'Andrei Balandin',
      year: '2020',
      material: 'Коллаж',
      size: 15,
      article: 'I00007',
      sizeFilter: '3',
      price: 4900,
      color: 'Зеленый',
      picture: 'https://imagizer.imageshack.com/img922/733/vDIySi.jpg',
      description: 'Работа Andrei Balandin',
    },
    {
      name: 'Любовь смерть, роботы и секс',
      author: '5fe050d48af2d06b642f117d',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Коллаж',
      sizeFilter: '2',
      article: 'P00001',
      price: 5900,
      color: 'Красный',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Ночное преступление',
      author: '5fe050d48af2d06b642f117d',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Скульптура',
      sizeFilter: '2',
      article: 'P00002',
      price: 8900,
      color: 'Синий',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Учеба вместо обеда',
      author: '5fe050d48af2d06b642f117d',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Скульптура',
      sizeFilter: '2',
      article: 'P00003',
      price: 18900,
      color: 'Фиолетовый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Эльбрус буткемп',
      author: '5fe050d48af2d06b642f117d',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Текстиль',
      sizeFilter: '2',
      article: 'P00004',
      price: 29900,
      color: 'Черно-белый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Троя и троянцы',
      author: '5fe050d48af2d06b642f117d',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Текстиль',
      sizeFilter: '3',
      article: 'P00005',
      price: 9900,
      color: 'Розовый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Крик и боль',
      author: '5fe050d48af2d06b642f117d',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Тиражные работы',
      sizeFilter: '1',
      article: 'P00006',
      price: 19900,
      color: 'Черно-белый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Нечто неизведанное',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Тиражные работы',
      sizeFilter: '1',
      article: 'P00007',
      price: 15900,
      color: 'Белый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Космос',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Фотография',
      sizeFilter: '1',
      article: 'P00008',
      price: 19900,
      color: 'Фиолетовый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
    {
      name: 'Правила созданы, чтобы их нарушать',
      author: '5fe050d48af2d06b642f117d',
      authorName: 'Dasha Kudinova',
      year: '2020',
      material: 'Фотография',
      sizeFilter: '3',
      article: 'P00009',
      price: 19900,
      color: 'Черно-белый',
      picture: 'https://imagizer.imageshack.com/img924/2554/FiUfiT.jpg',
      description: 'Работа Dasha Kudinova',
    },
  ]);
}
seeder1();
